services:
  - type: pserv
    name: rabbitmq
    runtime: docker
    envVars:
      - key: PORT
        value: "5672"
      - key: RABBITMQ_ERLANG_COOKIE
        generateValue: true
      - key: RABBITMQ_DEFAULT_USER
        value: rabbitmq
      - key: RABBITMQ_DEFAULT_PASS
        Value: rabbitmq
    disk:
      name: rabbit
      mountPath: /var/lib/rabbitmq
      sizeGB: 10
